"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import "./interview.css";
import "./voice.css";
import "./submit.css";

const bank={
 "Core HR & Workforce Structures":[
  {tier:1,q:"Explain legal employer, business unit and department using one real company example.",probe:"Which of these owns the employment contract?",signals:["legal employer","contract","business unit","department"]},
  {tier:2,q:"A client operates in the UK and India with shared Finance. Design the minimum enterprise and workforce structure.",probe:"What questions would you ask before creating two business units?",signals:["legislation","legal entity","legal employer","business unit","reference data"]},
  {tier:3,q:"A department transfer is effective next month, but reporting must show historical ownership correctly. How would you design and test it?",probe:"How do trees and effective dates affect the answer?",signals:["effective date","tree","version","history","report"]},
  {tier:4,q:"You inherit duplicate jobs, locations and departments after a merger. Describe your remediation and governance approach.",probe:"What would you avoid changing after go-live?",signals:["impact","mapping","end date","integration","governance","regression"]}],
 "Absence Management":[
  {tier:1,q:"What is the difference between an absence type and an absence plan?",probe:"Give an annual leave example.",signals:["type","plan","balance","entry"]},
  {tier:2,q:"Design annual leave for full-time and 0.6 FTE workers with new-hire proration.",probe:"Show the expected balance for one example worker.",signals:["fte","proration","eligibility","accrual","calculation"]},
  {tier:3,q:"A five-day balance is carried into the next year and expires on 31 March. Explain configuration and boundary testing.",probe:"How is carryover different from the ceiling?",signals:["carryover","expiry","ceiling","term","boundary"]},
  {tier:4,q:"A sickness absence grows from 10 to 25 days and must collect certification and reroute approval. Diagnose the end-to-end design.",probe:"What happens to the approval already completed?",signals:["certification","duration","approval","reroute","formula","test"]}],
 "Approvals & Journeys":[
  {tier:1,q:"Explain serial approval, parallel approval and FYI with examples.",probe:"Which one blocks the transaction?",signals:["serial","parallel","fyi","approval"]},
  {tier:2,q:"Design an approval where salary increases above 15% add Compensation Manager.",probe:"Which exact boundary values will you test?",signals:["condition","15","boundary","participant","test"]},
  {tier:3,q:"Current and receiving HRBP can be the same person during a transfer. How do you prevent duplicate and self-approval?",probe:"What if the receiving HRBP initiated the transaction?",signals:["duplicate","self approval","participant","skip","exception"]},
  {tier:4,q:"A global onboarding journey has shared and country tasks. Explain reuse, eligibility, allocation and operational support.",probe:"What happens to active journeys when the template changes?",signals:["eligibility","allocation","task group","notification","active","support"]}],
 "Reporting: OTBI, BIP & Extracts":[
  {tier:1,q:"When would you use OTBI rather than BI Publisher?",probe:"Which is better for a formatted employment letter?",signals:["analysis","subject area","pixel","template","bip"]},
  {tier:2,q:"An OTBI headcount report shows duplicates. Walk through how you diagnose the grain.",probe:"Why is DISTINCT not the first fix?",signals:["grain","assignment","join","primary","effective date"]},
  {tier:3,q:"Design a weekly benefits extract with changes only, SFTP delivery and reconciliation.",probe:"How will you handle a rerun without duplicates?",signals:["delta","watermark","sftp","control total","rerun","duplicate"]},
  {tier:4,q:"A large BIP report times out after a quarterly update. Explain diagnosis, tuning and release evidence.",probe:"How would you prove the change did not alter totals?",signals:["sql","filter","parameter","performance","reconcile","regression"]}],
 "Technical Integrations":[
  {tier:1,q:"Compare HDL, REST API and HCM Extracts by direction and typical use.",probe:"Which would you use for a 50,000-worker conversion?",signals:["inbound","outbound","bulk","real time","hdl","extract"]},
  {tier:2,q:"Build a worker HDL file with person, work relationship and assignment components. What keys and errors matter?",probe:"How do source keys help a repeat load?",signals:["source key","parent","component","effective date","error"]},
  {tier:3,q:"An API call times out after creating a target record. How do you retry safely?",probe:"Explain idempotency using a business key.",signals:["idempotency","business key","retry","timeout","duplicate","correlation"]},
  {tier:4,q:"Design a hire integration using an event, OIC orchestration and ServiceNow, including monitoring and replay.",probe:"How will the support team reconcile missed events?",signals:["event","oic","mapping","fault","replay","reconcile","monitor"]}],
 "Security & AOR":[
  {tier:1,q:"Explain job role, data role and security profile with one HR Specialist example.",probe:"Which part controls what data the user sees?",signals:["job role","data role","security profile","function","data"]},
  {tier:2,q:"Create access for a UK HR Specialist who must not see India workers.",probe:"What positive and negative tests will you run?",signals:["person security profile","data role","scope","uk","negative"]},
  {tier:3,q:"An HRBP must approve only workers in assigned departments. Explain AOR design and runtime resolution.",probe:"What happens when no active AOR exists?",signals:["aor","responsibility","department","effective date","representative"]},
  {tier:4,q:"A user has excessive access after a transfer. Describe diagnosis, remediation and audit evidence.",probe:"How do role mapping and data-role provisioning interact?",signals:["role mapping","provision","deprovision","inheritance","audit","least privilege"]}]
};

export default function InterviewSimulator({name,signOut}){
 const[area,setArea]=useState(Object.keys(bank)[0]),[years,setYears]=useState(3),[started,setStarted]=useState(false),[index,setIndex]=useState(0),[answer,setAnswer]=useState(""),[answers,setAnswers]=useState([]),[time,setTime]=useState(120),[finished,setFinished]=useState(false),[history,setHistory]=useState([]),[sessionId,setSessionId]=useState(""),[recording,setRecording]=useState(false),[audioBlob,setAudioBlob]=useState(null),[audioUrl,setAudioUrl]=useState(""),[micError,setMicError]=useState(""),[submitting,setSubmitting]=useState(false),[submitError,setSubmitError]=useState("");
 const recorder=useRef(null),stream=useRef(null),chunks=useRef([]),interviewTop=useRef(null);
 const questions=useMemo(()=>bank[area].filter(q=>q.tier<=Math.min(4,years)).slice(-3),[area,years]),current=questions[index];
 useEffect(()=>{fetch("/api/interviews").then(r=>r.json()).then(d=>setHistory(d.sessions||[]))},[finished]);
 useEffect(()=>{if(!started||finished)return;const t=setInterval(()=>setTime(x=>x>0?x-1:0),1000);return()=>clearInterval(t)},[started,finished,index]);
 function scoreAnswer(q,a){const text=a.toLowerCase(),hits=q.signals.filter(s=>text.includes(s)).length,depth=Math.min(2,Math.floor(a.trim().split(/\s+/).length/35));return Math.min(10,Math.round(hits/q.signals.length*8)+depth)}
 async function startRecording(){try{setMicError("");setSubmitError("");stream.current=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true}});chunks.current=[];const preferred=["audio/webm;codecs=opus","audio/webm","audio/mp4"].find(x=>MediaRecorder.isTypeSupported(x));const options={audioBitsPerSecond:24000,...(preferred?{mimeType:preferred}:{})},r=new MediaRecorder(stream.current,options);recorder.current=r;r.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};r.onstop=()=>{const blob=new Blob(chunks.current,{type:r.mimeType||preferred||"audio/webm"});setAudioBlob(blob);setAudioUrl(URL.createObjectURL(blob));stream.current?.getTracks().forEach(t=>t.stop())};r.start(1000);setRecording(true)}catch{setMicError("Microphone access was blocked. Allow microphone permission or use the written-answer option.")}}
 function stopRecording(){recorder.current?.stop();setRecording(false)}
 function discardRecording(){if(audioUrl)URL.revokeObjectURL(audioUrl);setAudioBlob(null);setAudioUrl("");setMicError("")}
 async function next(){if(submitting||(!answer.trim()&&!audioBlob))return;setSubmitting(true);setSubmitError("");try{let audioId;if(audioBlob){if(audioBlob.size>900*1024)throw new Error("This recording is too large to upload. Please discard it and record the answer again; new recordings are automatically reduced in size.");const f=new FormData();f.set("audio",new File([audioBlob],`answer-${index+1}.webm`,{type:audioBlob.type||"audio/webm"}));f.set("sessionId",sessionId);f.set("questionIndex",String(index));const response=await fetch("/api/interview-audio",{method:"POST",body:f}),raw=await response.text();let result={};try{result=raw?JSON.parse(raw):{}}catch{result={}}if(!response.ok||!result.id){const tooLarge=response.status===413||/payload too large/i.test(raw);throw new Error(tooLarge?"This recording is too large to upload. Please discard it and record the answer again.":result.error||"The voice answer could not be uploaded. Please try again.")}audioId=result.id}const item={q:current.q,a:answer,score:answer.trim()?scoreAnswer(current,answer):0,audioId},nextAnswers=[...answers,item];setAnswers(nextAnswers);setAnswer("");discardRecording();if(index<questions.length-1){setIndex(index+1);setTime(120);requestAnimationFrame(()=>interviewTop.current?.scrollIntoView({behavior:"smooth",block:"start"}))}else{setFinished(true);const typed=nextAnswers.filter(x=>x.a.trim()),percent=typed.length?Math.round(typed.reduce((s,x)=>s+x.score,0)/(typed.length*10)*100):0,strong=nextAnswers.filter(x=>x.score>=7).map(x=>x.q).join(" | "),gaps=nextAnswers.filter(x=>x.a&&x.score<7).map(x=>x.q).join(" | ");const response=await fetch("/api/interviews",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:sessionId,area,years,score:percent,strengths:strong,gaps,answers:nextAnswers})});if(!response.ok)throw new Error("The interview result could not be saved.")}}catch(e){setSubmitError(e instanceof Error?e.message:"The answer could not be submitted. Please try again.")}finally{setSubmitting(false)}}
 function begin(){setSessionId(crypto.randomUUID());setStarted(true)}
 function restart(){setStarted(false);setFinished(false);setIndex(0);setAnswers([]);setAnswer("");discardRecording();setTime(120)}
 const typedAnswers=answers.filter(x=>x.a.trim()),total=typedAnswers.reduce((s,x)=>s+x.score,0),percent=typedAnswers.length?Math.round(total/(typedAnswers.length*10)*100):0;

 return <main className="interview-shell">
  <header><a href="/">CHC · ORACLE HCM <span>MOCK INTERVIEW CENTRE</span></a><nav><a href="/dashboard">Dashboard</a><a href={signOut}>Sign out</a></nav></header>
  {!started?<section className="interview-setup"><div><small>LIVE PRACTICE · {name.toUpperCase()}</small><h1>Answer like a consultant.</h1><p>The interviewer adapts the depth to your chosen Oracle HCM area and claimed experience. Answer by voice for realistic speaking practice, or type when a microphone is unavailable.</p></div><form onSubmit={e=>{e.preventDefault();begin()}}><label>Interview area<select value={area} onChange={e=>setArea(e.target.value)}>{Object.keys(bank).map(x=><option key={x}>{x}</option>)}</select></label><label>Years of experience<select value={years} onChange={e=>setYears(Number(e.target.value))}>{[1,2,3,4].map(x=><option key={x} value={x}>{x} {x===1?"year":"years"}</option>)}</select></label><div className="interview-format"><b>{questions.length} questions</b><span>2 minutes each</span><span>Voice or written answer</span></div><button>Begin live interview →</button></form><aside><small>PREVIOUS ATTEMPTS</small>{history.slice(0,5).map(h=><article key={h.id}><b>{h.score}%</b><span>{h.area}</span><small>{h.years} YEARS · {new Date(h.createdAt).toLocaleDateString()}</small></article>)}{!history.length&&<p>No attempts yet.</p>}</aside></section>
  :!finished?<section className="live-interview" ref={interviewTop}><div className="interviewer"><span>CHC</span><div><b>Oracle HCM Interviewer</b><small>{area} · {years} YEARS</small></div><time className={time<30?"urgent":""}>{Math.floor(time/60)}:{String(time%60).padStart(2,"0")}</time></div><div className="question-progress"><span>QUESTION {index+1} OF {questions.length}</span><i><em style={{width:`${(index+1)/questions.length*100}%`}}/></i></div><article><small>INTERVIEW QUESTION</small><h2>{current.q}</h2><div className="probe"><b>FOLLOW-UP</b>{current.probe}</div>
   <section className={`voice-answer ${recording?"recording":""}`}><div><span className="mic">●</span><div><b>Record your spoken answer</b><p>Use your natural interview voice. Your trainer can replay the submitted recording.</p></div></div>{!recording&&!audioBlob&&<button onClick={startRecording}>Start recording</button>}{recording&&<button className="stop" onClick={stopRecording}>Stop recording</button>}{audioUrl&&<div className="audio-review"><audio controls src={audioUrl}/><button onClick={discardRecording}>Discard and retry</button></div>}{micError&&<em>{micError}</em>}</section>
   <div className="answer-divider"><span>OR</span></div><label>Type the points you would say<textarea value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Structure your answer: clarify the requirement → explain configuration/design → give an example → cover testing and exceptions…"/></label><div className="answer-footer"><span>{submitting?"Uploading and saving answer…":audioBlob?"Voice answer ready":`${answer.trim()?answer.trim().split(/\s+/).length:0} words`}</span><button disabled={submitting||recording||(!answer.trim()&&!audioBlob)} onClick={next}>{submitting?"Submitting…":index===questions.length-1?"Finish interview":"Submit and continue"} →</button></div>{submitError&&<p className="submit-error" role="alert">{submitError}</p>}</article></section>
  :<section className="interview-result"><small>INTERVIEW COMPLETE</small><h1>{percent}%</h1><h2>{answers.some(a=>a.audioId)?"Voice answers sent for trainer review":percent>=75?"Strong consultant-level answer":"Good practice — strengthen the missing evidence"}</h2><p>The percentage applies only to typed answers. Voice recordings are saved securely and require trainer review; they are not automatically transcribed or AI-scored.</p><div className="result-grid">{answers.map((a,i)=><article key={a.q}><span>{i+1}</span><div><b>{a.audioId?"VOICE SUBMITTED":`${a.score}/10`}</b><p>{a.q}</p><small>{a.audioId?"Available to your trainer for playback":a.score>=7?"Strong coverage":"Needs more configuration, testing or exception detail"}</small></div></article>)}</div><button onClick={restart}>Start another interview →</button></section>}
 </main>;
}
